language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - docker version
  - docker-compose version

before_script:
  - pip install docker-compose

script:
  # - docker-compose run --rm $(bash <(curl -s https://codecov.io/env)) -u root app sh -c "python manage.py test && flake8"
  # Using ROOT user in order to avoid 'PermissionError: [Errno 13] Permission denied: '/app/.coverage' error:
  # - docker-compose run -u root app sh -c "coverage run --source='.' manage.py test && coverage report && flake8 && codecov --commit=:sha"
  #- docker-compose run --rm -u root app sh -c "coverage run --source='.' manage.py test && coverage report && coverage xml && flake8"
  - docker-compose run app sh -c "python manage.py test && flake8"
